spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/danran_miaosha?userSSL=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password:
  activemq:
    broker-url: tcp://121.37.174.92:61616
    pool:
      enabled: false
      max-connections: 100
    packages:
      trust-all: true
    user: admin
    password: admin
mybatis:
  type-aliases-package: com.layui.book.pojo
  mapper-locations: classpath:/com/layui/book/Mapper/*Mapper.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
server:
  port: 8080
  servlet:
    context-path: /